### ISSUE TITLE
Bug: Latest update breaks tag-notes

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#239]
since the latest update (v.2.20), tag-notes have stopped working completely. Link-Notes, Folder-notes and everything else still shows up, but tag-notes do not show up anymore.

**Comment by SkepticMystic** [comment]
@chrisgrieser can you share the configuration of your tag note.
Something like

```yaml
---
BC-tag-note: ' #tag'
BC-tag-note-field: down
---
```

**Comment by SkepticMystic** [comment]
I've changed the behaviour of tag notes. This is the new logic:
1. Check for a `BC-tag-note-field`
2. If there isn't one for that tag note, use the chosen default tag note field from settings
3. If the user has chosen `<blank>` as their default, use the first field of all the fields
![image](https://user-images.githubusercontent.com/70717676/148359928-48f19ce9-ed3e-48a0-91f0-e3b95c486c06.png)

**Comment by chrisgrieser** [comment]
here is a screenshot. I have a total of 28 notes with the tag `#wissenschaftssoziologie`, only one of them shows up in breadcrumbs.

<img width="1268" alt="Screenshot 2022-01-06 11 58 03" src="https://user-images.githubusercontent.com/73286100/148372706-e61367a8-a7ac-4ae8-befb-8fe4e0e07136.png">

**Comment by chrisgrieser** [comment]
looking at the note, I think I found the issue. It's the only note that has `#tag` in its body, the others have tags in the yaml header.

I tested it adding a tag to the yaml header and then breadcrumbs indeed picks it up. So it's an issue of breadcrumbs not recognizing tags in the yaml anymore

**Comment by SkepticMystic** [comment]
Ahhh interesting, ok. I'll have to check what's going wrong there

**Comment by lkadre** [comment]
Similar issue but it's not picking up on tags in general, regardless of where they are. 

<img width="582" alt="Screen Shot 2022-01-06 at 17 58 21" src="https://user-images.githubusercontent.com/66343542/148451048-a5d67635-63bd-443c-9011-aef3481aae7e.png">

**Comment by dylan-wu** [comment]
Reproduced the bug with a simple case.

Create folder and add an empty note.

Here's a GIF:

![tag-notes-bug](https://user-images.githubusercontent.com/6586811/148459561-8b070bc2-ed9a-45f7-acaf-76fc08da77c1.gif)

**Comment by SkepticMystic** [comment]
Thank you everyone for the feedback. I'm trying to resolve this issue, but also struggling to reproduce it...
Can you try out the latest release and see if tag notes work again

**Comment by chrisgrieser** [comment]
nope, still the same here, only inline-text tags working for me

**Comment by SkepticMystic** [comment]
@chrisgrieser how about now in the latest release?

**Comment by SkepticMystic** [comment]
Wait, I see the error now. Give me a sec

**Comment by SkepticMystic** [comment]
@chrisgrieser the issue is that Obsidian doesn't recognise `tags: b, d` as actual tags. So I have to treat those differently. Not an issue, but that's why it wasn't detecting them after the change

**Comment by SkepticMystic** [comment]
Ok, for realsies. This issue should be fixed now

**Comment by chrisgrieser** [comment]
yep, works now :)

(Thanks for the fix! I'll leave it open as @lkadre reported an issue which could be different)

**Comment by lkadre** [comment]
Unfortunately it's still not working for me. I'm attaching the Console log, it seems to have some BC errors related to .addTagNotesTo Graph and .getAllTags.

[obsidian.md-1641765622815.log](https://github.com/SkepticMystic/breadcrumbs/files/7836060/obsidian.md-1641765622815.log)

**Comment by SkepticMystic** [comment]
@lkadre do you have any idea which notes are causing the errors? From your console logs (thanks!) I suspect the issue is a rogue tag, or a syntax Breadcrumbs isn't expecting. If you can send some examples of how you store your tags (in frontmatter), that'd be really helpful :)

**Comment by SkepticMystic** [comment]
@lkadre can you please post this in the console, and hit enter while focussed on a note with lots of tags in it. Check to see that all the tags are in the result, and that they all start with `#`.
```js
let getAllTags = (file, withHash = true) => {
    const { tags, frontmatter } = app.metadataCache.getFileCache(file);
    const allTags = [];

    tags?.forEach((t) => allTags.push(dropHash(t.tag)));

    [frontmatter?.tags ?? []].flat().forEach((t) => {
      splitAndTrim(t).forEach((innerT) => allTags.push(dropHash(innerT)));
    });
    [frontmatter?.tag ?? []].flat().forEach((t) => {
      splitAndTrim(t).forEach((innerT) => allTags.push(dropHash(innerT)));
    });

    return allTags.map((t) => (withHash ? "#" : "") + t.toLowerCase());
  };

let dropHash = (tag) =>
  tag.startsWith("#") ? tag.slice(1) : tag;

let splitAndTrim = (fields) => {
  if (fields === "") return [];
  else return fields.split(",").map((str) => str.trim());
};

getAllTags(app.workspace.getActiveFile())
```

**Comment by lkadre** [comment]
Tested on the first "child note" above. It does show all tags, but then has an error.


[obsidian.md-1641835047252.log](https://github.com/SkepticMystic/breadcrumbs/files/7840637/obsidian.md-1641835047252.log)


<img width="540" alt="Screen Shot 2022-01-10 at 14 15 29" src="https://user-images.githubusercontent.com/66343542/148808968-18d38745-383a-4b41-aa01-84c1ca4bf0fc.png">

**Comment by SkepticMystic** [comment]
@lkadre I don't think that error comes from Breadcrumbs... I don't recognise any of the things in it.
But that's even weirder, it finds all the tags correctly, and there aren't any errors. I'll have to keep testing

**Comment by SkepticMystic** [comment]
@lkadre I'm trying every test case I can possibly think of, and they all work...

**Comment by lkadre** [comment]
I turned off every other plugin (including Dataview) and reset to the default theme to see what happened. Still the same error...

```
Obsidian Developer Console
VM109:52737 loading breadcrumbs plugin
2VM109:53847 TypeError: Cannot read property 'split' of null
    at splitAndTrim (eval at <anonymous> (app.js:1), <anonymous>:22481:23)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:52673:17)
    at Array.forEach (<anonymous>)
    at BCPlugin.getAllTags (eval at <anonymous> (app.js:1), <anonymous>:52672:140)
    at hasThisTag (eval at <anonymous> (app.js:1), <anonymous>:53521:38)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:53528:69)
    at Array.filter (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:53528:18)
    at Array.forEach (<anonymous>)
    at BCPlugin.addTagNotesToGraph (eval at <anonymous> (app.js:1), <anonymous>:53514:22)
initGraphs @ VM109:53847
```

**Comment by SkepticMystic** [comment]
@lkadre Ahhh sorry! I see now you posted the log file. The error in the screenshot isn't BC-related, but this one definitely is.
Ok, I've added a patch in the latest release. I don't know why thee error you posted happens, but the patch should bypass it

**Comment by lkadre** [comment]
IT WORKS NOW!!! that was some detective work, thank you so much for your patience!

**Comment by SkepticMystic** [comment]
Ahh that's great to hear 😄 
Phew, that was a sneaky bug, indeed. 
The underlying issue is not actually resolved. I believe the cause it that one of your notes has a blank tags field `tag: ` or `tags: `. That would probably cause the problem you faced here. But the patch does overcome that, so all is well

**Comment by SkepticMystic** [comment]
Alright, I'm gonna close this issue then 😋
