### ISSUE TITLE
Bug: This note has no real or implied parents

### ISSUE THREAD

**Issue by JeremyMeissner** [SkepticMystic/breadcrumbs#344]
## Problem
**Describe the bug**
I try to use the plugin normally but It doesn't work. I've the message `This note has no real or implied parents` on my children file.

**To Reproduce**
1. Just install the plugin `breadcrumbs 2.55.2` on `Obsidian v0.13.23` on `Windows 10 20H2`
2. Create two files: `Me` and `Dad`

## Code
**Inside `Me`**
```
---
up: [[Dad]]
---
```

**Inside `Dad`**
```
---
down: [[Me]]
---
```
## Screenshots
|`Dad`|`Me`|
|---|---|
|![image](https://user-images.githubusercontent.com/34174370/154310321-f498ddd0-9da8-4347-a781-8258d62e4f74.png)|![image](https://user-images.githubusercontent.com/34174370/154310473-4a31a6fa-1962-4d1d-abed-b48f472da548.png)|
| |![image](https://user-images.githubusercontent.com/34174370/154310525-2c5f9eab-5390-4ad6-b509-44c8a9763d42.png)|

## Data.json
`{Vault}/.obsidian/plugins/breadcrumbs/data.json`
```json
{
  "addDendronNotes": false,
  "addDateNotes": false,
  "aliasesInIndex": false,
  "alphaSortAsc": false,
  "altLinkFields": [],
  "CSVPaths": "",
  "dateFormat": "YYYY-MM-DD",
  "dateNoteFormat": "yyyy-MM-dd",
  "dateNoteField": "next",
  "dataviewNoteField": "up",
  "dateNoteAddMonth": "",
  "dateNoteAddYear": "",
  "debugMode": "WARN",
  "defaultView": true,
  "dendronNoteDelimiter": ".",
  "dendronNoteField": "up",
  "downViewWrap": false,
  "dotsColour": "#000000",
  "dvWaitTime": 5000,
  "enableAlphaSort": true,
  "enableRelationSuggestor": false,
  "fieldSuggestor": true,
  "filterImpliedSiblingsOfDifferentTypes": false,
  "jugglLayout": "hierarchy",
  "limitWriteBCCheckboxes": [],
  "CHECKBOX_STATES_OVERWRITTEN": false,
  "gridDots": false,
  "gridHeatmap": false,
  "heatmapColour": " hsl(  317,  100%, calc( 90% - 2%) )",
  "hierarchyNotes": [
    ""
  ],
  "HNUpField": "",
  "indexNotes": [
    ""
  ],
  "namingSystemField": "",
  "namingSystemRegex": "",
  "namingSystemSplit": ".",
  "namingSystemEndsWithDelimiter": false,
  "refreshOnNoteChange": false,
  "useAllMetadata": true,
  "openMatrixOnLoad": true,
  "openStatsOnLoad": true,
  "openDuckOnLoad": false,
  "openDownOnLoad": true,
  "overflowMLView": true,
  "parseJugglLinksWithoutJuggl": false,
  "showNameOrType": true,
  "showRelationType": true,
  "regexNoteField": "",
  "relSuggestorTrigger": "\\",
  "rlLeaf": true,
  "showAllPathsIfNoneToIndexNote": false,
  "showAllAliases": true,
  "showBCs": true,
  "showBCsInEditLPMode": false,
  "showRefreshNotice": true,
  "showImpliedRelations": true,
  "showTrail": true,
  "showGrid": true,
  "showJuggl": false,
  "showPrevNext": true,
  "sortByNameShowAlias": false,
  "squareDirectionsOrder": [
    0,
    1,
    2,
    3,
    4
  ],
  "limitTrailCheckboxes": [],
  "limitJumpToFirstFields": [],
  "showAll": false,
  "noPathMessage": "This note has no real or implied parents",
  "tagNoteField": "",
  "threadIntoNewPane": false,
  "threadingTemplate": "{{field}} of {{current}}",
  "threadingDirTemplates": {
    "up": "",
    "same": "",
    "down": "",
    "next": "",
    "prev": ""
  },
  "threadUnderCursor": false,
  "trailSeperator": "→",
  "treatCurrNodeAsImpliedSibling": false,
  "trimDendronNotes": false,
  "respectReadableLineLength": true,
  "userHiers": [
    {
      "up": [
        "up"
      ],
      "same": [
        "same"
      ],
      "down": [
        "down"
      ],
      "next": [
        "next"
      ],
      "prev": [
        "prev"
      ]
    }
  ],
  "writeBCsInline": false,
  "showWriteAllBCsCmd": false,
  "visGraph": "Force Directed Graph",
  "visRelation": "Parent",
  "visClosed": "Real",
  "visAll": "All",
  "wikilinkIndex": true,
  "impliedRelations": {
    "siblingIdentity": false,
    "sameParentIsSibling": true,
    "siblingsSiblingIsSibling": false,
    "siblingsParentIsParent": false,
    "parentsSiblingsIsParents": false,
    "parentsParentsIsParent": false,
    "cousinsIsSibling": false
  },
  "refreshOnNoteSave": false,
  "showUpInJuggl": false
}
```

**Comment by SkepticMystic** [comment]
Hey @JeremyMeissner, thanks for the detailed report!
I believe the issue is an old bug that should've been resolved by now... not sure why it happens on the latest version.
But if you go to `Settings > Views > Trail/Grid View > Limit Trail Fields`, all of those checkboxes should be **checked**, and I suspect they aren't. Please confirm if checking them resolves the issue for you

**Comment by JeremyMeissner** [comment]
Hey @SkepticMystic, there is only one checkbox here, I checked it, restarted Obsidian but the problem is still there.
![image](https://user-images.githubusercontent.com/34174370/154326722-a9f07123-8f25-43c2-b622-6cd021d6e46f.png)

**Comment by chaddm** [comment]
@JeremyMeissner I have the same issue.  New user to the plugin, fresh install.  I figured out the issue.  The documentation suggests using 'parent', 'child', etc for relationships; however, the default install's hierarchy is `up`, `same`, `down`, etc.  I added a new hierarchy as per the documentation and used `refresh index` and it works.

@SkepticMystic I would recommend updating the documentation or changing the default to include the documentation's format.

**Comment by JeremyMeissner** [comment]
Hi @chaddm. I first had this problem, but on my side even by changing to `up` and `down` I still have the problem :(

**Comment by chaddm** [comment]
@JeremyMeissner A few things:

- You have to match the names in the hierarchy exactly.
- A page won't get the trail unless it has a parent, explicitly marked or implied from another note.  So `A` will not have the trail, but `B` will it if `B` has `A` marked as a parent or `A` has `B` marked as a child.
- By default, it doesn't update unless you hit the `Refresh Index` button or use the command palette.  There are options to make it more automatic.
- There are switches to allow more ways to imply relationships.

**Comment by SkepticMystic** [comment]
@JeremyMeissner can you send your settings again now that you've changed the checkboxes

**Comment by JeremyMeissner** [comment]
Actually the problem has been solved by reinstalling the plugin.
Still, here is my `data.json` as you ask. 
```JSON
{
  "addDendronNotes": false,
  "addDateNotes": false,
  "aliasesInIndex": false,
  "alphaSortAsc": false,
  "altLinkFields": [],
  "CSVPaths": "",
  "dateFormat": "YYYY-MM-DD",
  "dateNoteFormat": "yyyy-MM-dd",
  "dateNoteField": "next",
  "dataviewNoteField": "up",
  "dateNoteAddMonth": "",
  "dateNoteAddYear": "",
  "debugMode": "WARN",
  "defaultView": true,
  "dendronNoteDelimiter": ".",
  "dendronNoteField": "up",
  "downViewWrap": false,
  "dotsColour": "#000000",
  "dvWaitTime": 5000,
  "enableAlphaSort": true,
  "enableRelationSuggestor": false,
  "fieldSuggestor": true,
  "filterImpliedSiblingsOfDifferentTypes": false,
  "jugglLayout": "hierarchy",
  "limitWriteBCCheckboxes": [],
  "CHECKBOX_STATES_OVERWRITTEN": false,
  "gridDots": false,
  "gridHeatmap": false,
  "heatmapColour": " hsl(  317,  100%, calc( 90% - 2%) )",
  "hierarchyNotes": [
    ""
  ],
  "HNUpField": "",
  "indexNotes": [
    ""
  ],
  "namingSystemField": "",
  "namingSystemRegex": "",
  "namingSystemSplit": ".",
  "namingSystemEndsWithDelimiter": false,
  "refreshOnNoteChange": false,
  "useAllMetadata": true,
  "openMatrixOnLoad": true,
  "openStatsOnLoad": true,
  "openDuckOnLoad": false,
  "openDownOnLoad": true,
  "overflowMLView": true,
  "parseJugglLinksWithoutJuggl": false,
  "showNameOrType": true,
  "showRelationType": true,
  "regexNoteField": "",
  "relSuggestorTrigger": "\\",
  "rlLeaf": true,
  "showAllPathsIfNoneToIndexNote": false,
  "showAllAliases": true,
  "showBCs": true,
  "showBCsInEditLPMode": false,
  "showRefreshNotice": true,
  "showImpliedRelations": true,
  "showTrail": true,
  "showGrid": true,
  "showJuggl": false,
  "showPrevNext": true,
  "sortByNameShowAlias": false,
  "squareDirectionsOrder": [
    0,
    1,
    2,
    3,
    4
  ],
  "limitTrailCheckboxes": [
    "up"
  ],
  "limitJumpToFirstFields": [],
  "showAll": false,
  "noPathMessage": "This note has no real or implied parents",
  "tagNoteField": "",
  "threadIntoNewPane": false,
  "threadingTemplate": "{{field}} of {{current}}",
  "threadingDirTemplates": {
    "up": "",
    "same": "",
    "down": "",
    "next": "",
    "prev": ""
  },
  "threadUnderCursor": false,
  "trailSeperator": "→",
  "treatCurrNodeAsImpliedSibling": false,
  "trimDendronNotes": false,
  "respectReadableLineLength": true,
  "userHiers": [
    {
      "up": [
        "up"
      ],
      "same": [
        "same"
      ],
      "down": [
        "down"
      ],
      "next": [
        "next"
      ],
      "prev": [
        "prev"
      ]
    }
  ],
  "writeBCsInline": false,
  "showWriteAllBCsCmd": false,
  "visGraph": "Force Directed Graph",
  "visRelation": "Parent",
  "visClosed": "Real",
  "visAll": "All",
  "wikilinkIndex": true,
  "impliedRelations": {
    "siblingIdentity": false,
    "sameParentIsSibling": true,
    "siblingsSiblingIsSibling": false,
    "siblingsParentIsParent": false,
    "parentsSiblingsIsParents": false,
    "parentsParentsIsParent": false,
    "cousinsIsSibling": false
  },
  "refreshOnNoteSave": false,
  "showUpInJuggl": false
}
```
